name: some_discarded_name
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - scipy
  - h5py
  - matplotlib
  - rise  # For presentations from Jupyter notebooks
  - ipywidgets  # For interactive sliders and such
  - pip
  - pip:
    - gw-matched-filtering-demo
